# 微信支付配置参数
wxpay:
  # 商户号
  mch-id: xxxxxxxxxxxx
  # 商户API证书序列号
  mch-serial-no: xxxxxxxxxxxxxxxx
  # 商户私钥文件
  private-key-path: cert/apiclient_key.pem    // 替换成自己的
  # APIv3密钥
  api-v3-key: xxxxxxxxxxxxxxxxxxxxx
  # AppID
  appid: xxxxxxxx
  # 微信服务器地址
  domain: https://api.mch.weixin.qq.com
  # 回调地址  请使用自己的回调地址
  notify-domain: xxxxxxxxxxxxxxxx


